### ISSUE TITLE
Fails when doing the callback with COPY_META

### ISSUE THREAD

**Issue by jllorente** [oremanj/python-netfilterqueue#23]
Hi,
I am trying to bind to an NFQUEUE configured with COPY_META only, as I only intend to retrieve the packet mark. I would think that maybe when a Packet() is created, we should indicate the operation mode of the queue somehow...

I'm using the latest version of the code :)

```
Exception ignored in: 'netfilterqueue.global_callback'
Traceback (most recent call last):
  File "netfilterqueue.pyx", line 69, in netfilterqueue.Packet.set_nfq_data (netfilterqueue.c:2193)
OSError: Failed to get payload of packet.
```

**Comment by strictlymike** [comment]
Bump. I saw this too, last night, after updating my local copy. I think it's an important one because a lot of users might be able to get around the static buffer size by just copying/modifying/updating headers, but because this doesn't work, some users will need to modify the pyx file and recompile.
